extend-exclude=[
    "misc_python_utils/rustedpy/result.py", # mostly copypaste from rusted-py trying to stay close to original
    "misc_python_utils/rustedpy/maybe.py", # mostly copypaste from rusted-py trying to stay close to original
]